import { ReactElement, useEffect, useState } from 'react';

import Head from 'next/head';
import { useRouter } from 'next/router';

import { routes } from '../../data/routes';

import { LinkObject } from '../../utils/parseHTML';

import styles from '../../styles/Articles.module.css';

import Layout from '../../components/Layout';

export default function ArticlesList() {
  const router = useRouter();
  const { slug } = router.query;

  const [articles, setArticles] = useState<LinkObject[]>([]);

  useEffect(() => {
    setArticles([]);

    (async () => {
      const response = await fetch(`/api/articles/${slug}`);
      const result = await response.json();
      setArticles(result.links);
    })();

  }, [slug]);

  // Get the article title from the routes list using the slug
  const sectionTitle = routes.find((route) => route.path === slug)?.name;

  return (
    <section className={styles.wrapper}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h2>
        {sectionTitle}
      </h2>

      {articles.length === 0 && <p>Loading...</p>}
      <div className={styles.articleList}>
        {articles.map((article, index) => {
          return (
            <a
              key={index}
              href={article.href}
              target="_blank"
              rel="noopener noreferrer"
            >
              <span>{index + 1}.</span>
              <span>{article.text}</span>
            </a>
          );
        })}
      </div>
    </section>
  );
};

ArticlesList.getLayout = function getLayout(page: ReactElement) {
  return (
    <Layout>
      {page}
    </Layout>
  );
};
